version: '3'

services:
  broker-service:
  # sets the parameters required for building the image
  build:
      # sets the directory for the microservice
      context: broker
      # sets the image name for the microservice
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      - SERVICE_PORT=80
    deploy:
      mode: replicated
      replicas: 1
      
